services:
  mariadb:
    image: mariadb:12.1.2-ubi10
    container_name: techbit-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "@RootPasswordSecure123"
      MARIADB_DATABASE: techbit_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
